### ISSUE TITLE
Bug when joining a chatroom 

### ISSUE THREAD

**Issue by nathan-a-macleod** [jacob-macleod/LinguaLearn#14]
When you are signed in, if you go to the "Join a chatroom" page, then go out of that page, it automatically joins you into that chatroom even if you haven't pressed "join".

**Comment by jacob-macleod** [comment]
Thank you, I'll work on this.

Below is some diagnostic information for myself.


When the create chatroom button is pressed, then another button like the add chatroom button, the chatroom selected in the drop down select box is added to the user. I believe this to be due to the fact that the buttons are considered to be `select` buttons - try changing the type property to `type="button"`

**Comment by jacob-macleod** [comment]
I have now fixed this bug
