### ISSUE TITLE
Implement private chatrooms

### ISSUE THREAD

**Issue by nathan-a-macleod** [jacob-macleod/LinguaLearn#15]

**Comment by jacob-macleod** [comment]
@nathan-a-macleod thanks for submitting this issue. Do you mean create a system where there are private chatrooms? If so, maybe it would be better to enter them with a link and a code, and a possible password in addition to that

**Comment by nathan-a-macleod** [comment]
Yep something like that as currently anyone can join any chat room

**Comment by jacob-macleod** [comment]
Ok, I'll work on this. For reference to myself, here are the aims of my implementation:

- [x] Allow chatrooms to be created as public or private
- [x] If private, each chatroom has a unique code associated with it and a password
- [x] Going to /chatrooms/join?code=`code` will join that chatroom
- [x]  The restricted chatroom does not appear on the list of public chatrooms
- [x]  On the createChatroom page, users can enter a code. When they click the button, they will be taken to  /chatrooms/join?code=`chatroom code`
- I do not think a password is needed because the code would function like a password

**Comment by jacob-macleod** [comment]
TODO list:
Right now, the chatroom code can be entered and in theory, it should let you join the chatroom if correct
* ~~Add an information icon to dashboard by each flashcard~~
* ~~When clicked, it opens an info page with each user, a button to leave the chatroom and a button to share the chatroom~~
* ~~When you click share it gives you a popup with the code telling you to copy it and that people can use the code to join chatrooms~~
* ~~It also give you a join link~~
* ~~The popup can then be closed~~
* ~~The functionality should work for public and private chatrooms, but it is the only way to join private chatrooms~~
* ~~The join link can be shared with others so they can join the chatroom with one click~~
* ~~When you create a new chatroom, you can choose whether it is public or private~~
* ~~It will be stored in the csv file with public or private added on the end~~

BUG FIXES
* ~~Make it so you can't join the same chatroom twice!~~
